# Generated by Django 4.2.5 on 2023-09-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp_question', '0002_remove_card_link_card_link_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('solution', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='link_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
