# Generated by Django 4.2.5 on 2023-09-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp_question', '0003_solution_alter_card_link_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_math',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_no', models.IntegerField()),
                ('question', models.TextField()),
                ('opt_name', models.CharField(max_length=100)),
                ('opt_id1', models.CharField(max_length=100)),
                ('opt_id2', models.CharField(max_length=100)),
                ('opt_id3', models.CharField(max_length=100)),
                ('opt_id4', models.CharField(max_length=100)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
