# Generated by Django 4.2.5 on 2023-09-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp_question', '0004_question_math_delete_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_math',
            name='opt_for1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question_math',
            name='opt_for2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question_math',
            name='opt_for3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question_math',
            name='opt_for4',
            field=models.CharField(default='', max_length=100),
        ),
    ]
