# Generated by Django 4.2.5 on 2023-09-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp_question', '0005_question_math_opt_for1_question_math_opt_for2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_math',
            name='solution',
            field=models.CharField(default='', max_length=100),
        ),
    ]
