# Generated by Django 4.2.5 on 2023-09-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dp_question', '0006_question_math_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_math',
            name='opt_for1',
        ),
        migrations.RemoveField(
            model_name='question_math',
            name='opt_for2',
        ),
        migrations.RemoveField(
            model_name='question_math',
            name='opt_for3',
        ),
        migrations.RemoveField(
            model_name='question_math',
            name='opt_for4',
        ),
        migrations.RemoveField(
            model_name='question_math',
            name='opt_id1',
        ),
        migrations.RemoveField(
            model_name='question_math',
            name='opt_id2',
        ),
        migrations.RemoveField(
            model_name='question_math',
            name='opt_id3',
        ),
        migrations.RemoveField(
            model_name='question_math',
            name='opt_id4',
        ),
        migrations.RemoveField(
            model_name='question_math',
            name='opt_name',
        ),
    ]
