# Generated by Django 4.2.5 on 2023-09-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp_question', '0010_alter_question_math_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_math',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='B', max_length=1),
        ),
    ]
