# Generated by Django 4.2.5 on 2023-09-23 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dp_question', '0014_question_reas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question_reas',
        ),
    ]
